### ISSUE TITLE
Form Opening

### ISSUE THREAD

**Issue by uzairahmed** [PrinceLordPrime/AnonERP#1]
Name of the feature | Issue | Status
-- | -- | --
DB | Error Occurred during retrieving of Data from DB on Form opening | Not Resolved
After Login | Main Page Loads Two Times | Not Resolved

**Comment by PrinceLordPrime** [comment]
Name of the feature | Issue | Status
-- | -- | --
DB | Error Occurred during retrieving of Data from DB on Form opening | Not Resolved
After Login | Main Page Loads Two Times | RESOLVED

**Comment by PrinceLordPrime** [comment]
One Issue resolved of 2 Instances

**Comment by PrinceLordPrime** [comment]
Name of the feature | Issue | Status
-- | -- | --
DB | Error Occurred during retrieving of Data from DB on Form opening | RESOLVED
After Login | Main Page Loads Two Times | RESOLVED
